This Python script processes a text file with stored grades, calculates student averages by building & course, and generates separate CSV files.

- Imports libraries for data manipulation (pandas) and file handling (os).
- Retrieves the user's working directory (with error handling).
- Defines file name, building & course filters, and optional course names.
- Creates a function to check and read the text file as CSV with tab delimiter.
- Reads the file and stores the data in a DataFrame (df).
- Processes the data (filtering, calculations, CSV generation) if successful.
- Exits with an error message if the file cannot be read.

In [9]:
import pandas as pd
import os

# Automatic Directory Retrieval
# Get the user's current working directory (consider error handling)
try:
    dir = os.getcwd()
except OSError as e:
    print(f"Error retrieving current directory: {e}")
    exit(1)

# File Name
filename = "StoredGrades_export.txt"

# Building Filters
B1_Filter = 255  # Charles Boehm
B2_Filter = 260  # Pennwood
B3_Filter = 265  # William Penn

# Course Filters
C1_filter = 'PE6'  # Physical Education 6th Grade
C2_filter = 'PE7'  # Physical Education 7th Grade
C3_filter = 'PE8'  # Physical Education 8th Grade

# Course Names
C1_name = 'Phys Ed 6th'
C2_name = 'Phys Ed 7th'
C3_name = 'Phys Ed 8th'

# Function to check and read the text file
def check_and_read_text_file(filepath):
    if os.path.isfile(filepath):
        print(f"File {filename} found in {dir}.")
        try:
            df = pd.read_csv(filepath, delimiter="\t")
            print(f"{filename} successfully uploaded.")
            return df  # Return the DataFrame for further use
        except pd.errors.ParserError as e:
            print(f"Error parsing text file: {e}")
            return None  # Indicate failure to read the file
    else:
        print(f"File {filename} not found in {dir}.")
        return None  # Indicate file not found

# Check for and read the text file
df = check_and_read_text_file(os.path.join(dir, filename))

# Further processing with the DataFrame (if successfully read)
if df is not None:
    # Your code using the DataFrame (e.g., applying filters, exporting to Excel)
    pass
else:
    print("Exiting due to previous errors.")  # Informative exit message

# Suppress the excel/openpyxl warning (optional)
import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='openpyxl')

File StoredGrades_export.txt found in C:\Users\rkroker\Documents\Code\Python\PE Grade Average.
StoredGrades_export.txt successfully uploaded.

The next code block filters the data from the initial DataFrame (df) based on building and course combinations.

- Building-Level Filtering: It creates three new DataFrames: CBdf, PWdf, and WPdf. Each DataFrame contains data for a specific building by filtering the original DataFrame (df) based on the SchoolID column and the corresponding building filter constants (B1_Filter, B2_Filter, B3_Filter).
- Course-Level Filtering: Within each building-specific DataFrame, it further filters data for three separate courses (PE6, PE7, PE8). This results in nine DataFrames (e.g., CB_PE6_df, CB_PE7_df, CB_PE8_df, etc.) containing data for specific building-course combinations.
- head() method (Optional): The .head() method is called on CB_PE6_avg for debugging and guiding the reader along with the dataframe creation.

In essence, this code segment takes the initial data and creates more granular DataFrames for each building and course combination.

In [11]:
# Filter data for specific buildings
CBdf = df[df['SchoolID'] == B1_Filter]
PWdf = df[df['SchoolID'] == B2_Filter]
WPdf = df[df['SchoolID'] == B3_Filter]

# Filter data for the specific course ID
CB_PE6_df = CBdf[CBdf['Course_Number'] == 'PE6']
CB_PE7_df = CBdf[CBdf['Course_Number'] == 'PE7']
CB_PE8_df = CBdf[CBdf['Course_Number'] == 'PE8']

PW_PE6_df = PWdf[PWdf['Course_Number'] == 'PE6']
PW_PE7_df = PWdf[PWdf['Course_Number'] == 'PE7']
PW_PE8_df = PWdf[PWdf['Course_Number'] == 'PE8']

WP_PE6_df = WPdf[WPdf['Course_Number'] == 'PE6']
WP_PE7_df = WPdf[WPdf['Course_Number'] == 'PE7']
WP_PE8_df = WPdf[WPdf['Course_Number'] == 'PE8']

CB_PE6_df.head()

,dcid,AB_Course_Cmp_Ext_Crd,AB_Course_Cmp_Fun_Flg,AB_Course_Cmp_Fun_Sch,AB_Course_Cmp_Met_Cd,AB_Course_Cmp_Sta_Cd,AB_Course_Eva_Pro_Cd,AB_Dipl_Exam_Mark,AB_Final_Mark,AB_Lng_Cd,...,SectionID,StoreCode,StudentID,Tardies,Teacher_Name,TermBinsName,TermID,TRANSACTION_DATE,WHOMODIFIEDID,WHOMODIFIEDTYPE
1075,6345644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27954,Q1,8897,0,"Howe, David",S1,3313,3/20/24,3,a
1076,6345646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27954,Q1,8871,0,"Howe, David",S1,3313,3/20/24,3,a
1077,6345647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28229,Q1,8519,0,"Howe, David",S1,3313,3/20/24,3,a
1078,6345656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28043,Q1,11206,0,"Howe, David",S1,3313,3/20/24,3,a
1079,6345661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28043,Q1,8585,0,"Howe, David",S1,3313,3/20/24,3,a

The next code calculates the average percentage per student for each course within each building.

- Iterates Through Courses: The code loops through three courses (PE6, PE7, PE8).
- Calculates Average Percent per Student: For each course within a building (e.g., CB_PE6_df, CB_PE7_df, etc.), it calculates the average of the "Numeric" column grouped by the "StudentID" column. This results in a DataFrame for each building-course combination containing the average percentage for each student. The to_frame method converts the Series result to a DataFrame with a named column ("Avg_Percent").
- Assigns Result to Variable: The calculated DataFrame containing student IDs and average percentages is assigned to a variable with a descriptive name (e.g., CB_PE6_avg, PW_PE7_avg, etc.).
- head() method (Optional): The .head() method is called on CB_PE6_avg for debugging and guiding the reader along with the dataframe creation.
  
Overall, this code snippet calculates the core metric of your script: the average percentage achieved by each student in each physical education course offered by each building.

In [13]:
# Calculate the average percent per student (use filtered data if applicable)
# PE6
CB_PE6_avg = CB_PE6_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
PW_PE6_avg = PW_PE6_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
WP_PE6_avg = WP_PE8_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
# PE7
CB_PE7_avg = CB_PE7_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
PW_PE7_avg = PW_PE7_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
WP_PE7_avg = WP_PE7_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
#PE8
CB_PE8_avg = CB_PE8_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
PW_PE8_avg = PW_PE8_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')
WP_PE8_avg = WP_PE8_df.groupby('StudentID')['Numeric'].mean().to_frame(name='Avg_Percent')

CB_PE6_avg.head()

           Avg_Percent
StudentID
7393         67.727500
7397         98.292500
7752        100.000000
7849         99.715000
7874         99.243333

The next code segment defines a function to assign letter grades based on average percentage and applies it to each building-course DataFrame.

- Function Definition: It defines a function named get_letter_grade that takes an average percentage as input. The function uses a series of if-elif-else statements to assign letter grades based on pre-defined thresholds:
    - 90% or above: 'A'
    - 80% or above: 'B'
    - 70% or above: 'C'
    - 60% or above: 'D'
    - Below 60%: 'F'
- Applying the Function: The code iterates through each building-course DataFrame (e.g., CB_PE6_avg, PW_PE7_avg, etc.). It creates a new column named "Letter Grade" and applies the get_letter_grade function to the "Avg_Percent" column using the .apply method. This assigns a letter grade to each student based on their calculated average percentage.
- head() method (Optional): The .head() method is called on CB_PE6_avg for debugging and guiding the reader along with the dataframe creation.

In essence, this code snippet translates the calculated average percentages into a more user-friendly letter grading system for each student's performance in each course.

In [15]:
# Define a function to assign letter grades based on average percentage
def get_letter_grade(avg_percent):
    if avg_percent >= 90:
        return 'A'
    elif avg_percent >= 80:
        return 'B'
    elif avg_percent >= 70:
        return 'C'
    elif avg_percent >= 60:
        return 'D'
    else:
        return 'F'

# Apply the function to create a new 'Letter Grade' column
# student_course_avg['Letter Grade'] = student_course_avg['percent'].apply(get_letter_grade)
# PE6
CB_PE6_avg['Letter Grade'] = CB_PE6_avg['Avg_Percent'].apply(get_letter_grade)
PW_PE6_avg['Letter Grade'] = PW_PE6_avg['Avg_Percent'].apply(get_letter_grade)
WP_PE6_avg['Letter Grade'] = WP_PE6_avg['Avg_Percent'].apply(get_letter_grade)
# PE7
CB_PE7_avg['Letter Grade'] = CB_PE7_avg['Avg_Percent'].apply(get_letter_grade)
PW_PE7_avg['Letter Grade'] = PW_PE7_avg['Avg_Percent'].apply(get_letter_grade)
WP_PE7_avg['Letter Grade'] = WP_PE7_avg['Avg_Percent'].apply(get_letter_grade)
# PE8
CB_PE8_avg['Letter Grade'] = CB_PE8_avg['Avg_Percent'].apply(get_letter_grade)
PW_PE8_avg['Letter Grade'] = PW_PE8_avg['Avg_Percent'].apply(get_letter_grade)
WP_PE8_avg['Letter Grade'] = WP_PE8_avg['Avg_Percent'].apply(get_letter_grade)

CB_PE6_avg.head()

           Avg_Percent Letter Grade
StudentID
7393         67.727500            D
7397         98.292500            A
7752        100.000000            A
7849         99.715000            A
7874         99.243333            A

The next code segment defines a function to assign GPA points based on letter grades and applies it to each building-course DataFrame.

- Function Definition: It defines a function named get_GPA_points that takes a letter grade as input. The function uses a series of if statements to assign GPA points based on the letter grade:
    - 'A': 4 points
    - 'B': 3 points
    - 'C': 2 points
    - 'D': 1 point
    - Other letters (including 'F'): 0 points
- Applying the Function: Similar to the previous step, the code iterates through each building-course DataFrame (e.g., CB_PE6_avg, PW_PE7_avg, etc.). It creates a new column named "GPA Points" and applies the get_GPA_points function to the "Letter Grade" column using the .apply method. This assigns GPA points to each student based on their letter grade.
- head() method (Optional): The .head() method is called on CB_PE6_avg for debugging and guiding the reader along with the dataframe creation.

Overall, this code snippet converts the letter grades into a numerical representation (GPA points) for further calculations or analysis.

In [17]:
# Define a function to assign GPA Points based on assigned Letter Grade
def get_GPA_points(letter_grade):
    if letter_grade == 'A':
        return 4
    if letter_grade == 'B':
        return 3
    if letter_grade == 'C':
        return 2
    if letter_grade == 'D':
        return 1
    else:
        return 0


# Apply the function to create a new 'GPA Points' column
# student_course_avg['GPA Points'] = student_course_avg['Letter Grade'].apply(get_GPA_points)
# PE6
CB_PE6_avg['GPA Points'] = CB_PE6_avg['Letter Grade'].apply(get_GPA_points)
PW_PE6_avg['GPA Points'] = PW_PE6_avg['Letter Grade'].apply(get_GPA_points)
WP_PE6_avg['GPA Points'] = WP_PE6_avg['Letter Grade'].apply(get_GPA_points)
# PE7
CB_PE7_avg['GPA Points'] = CB_PE7_avg['Letter Grade'].apply(get_GPA_points)
PW_PE7_avg['GPA Points'] = PW_PE7_avg['Letter Grade'].apply(get_GPA_points)
WP_PE7_avg['GPA Points'] = WP_PE7_avg['Letter Grade'].apply(get_GPA_points)
# PE8
CB_PE8_avg['GPA Points'] = CB_PE8_avg['Letter Grade'].apply(get_GPA_points)
PW_PE8_avg['GPA Points'] = PW_PE8_avg['Letter Grade'].apply(get_GPA_points)
WP_PE8_avg['GPA Points'] = WP_PE8_avg['Letter Grade'].apply(get_GPA_points)

CB_PE6_avg.head()

           Avg_Percent Letter Grade  GPA Points
StudentID
7393         67.727500            D           1
7397         98.292500            A           4
7752        100.000000            A           4
7849         99.715000            A           4
7874         99.243333            A           4

This code snippet focuses on enriching each building-course DataFrame with additional columns containing pre-defined or course-specific information.

- Adding Course Information:
    - Course Number: It adds a "Course Number" column to each DataFrame and assigns the corresponding course filter value (e.g., C1_filter for PE6, C2_filter for PE7, etc.)
    - Course Name (Optional): Similar to the number, it adds an optional "Course Name" column using the corresponding course name filter values (e.g., C1_name for PE6).
- Adding Credit Information:
    - Earned Credit Hours: It adds a "EarnedCrHrs" column with a value of 0.5 to all DataFrames, likely representing the credit earned for each course.
    - Potential Credit Hours: It adds a "PotentialCrHrs" column with a value of 0.5 to all DataFrames, potentially representing the maximum credit attainable for each course.
- Adding School Information:
    - Grade Level: It adds a "Grade_Level" column to each DataFrame and assigns the corresponding grade level based on the course filter (e.g., 6 for PE6, 7 for PE7, etc.).
    - Credit Type: It adds a "CreditType" column with a value of "PE" to all DataFrames, indicating the course type.
    - Store Code: It adds a "StoreCode" column with a value of "Y1" to all DataFrames, likely an internal code.
    - Term ID: It adds a "TermID" column with a value of 3300 to all DataFrames, potentially representing the term or semester.
    - School ID: It adds a "SchoolID" column and assigns the corresponding school ID based on the building filter used to generate the DataFrame (e.g., 255 for Charles Boehm, 260 for Pennwood, etc.).
- head() method (Optional): The .head() method is called on CB_PE6_avg for debugging and guiding the reader along with the dataframe creation.
  
Overall, this code snippet adds context and potentially prepares the data for further analysis and uploading back into SIS.

In [19]:
# Add a new column named 'Course Number' with value of the originally filtered course for all rows
# PE6
CB_PE6_avg['Course Number'] = C1_filter
PW_PE6_avg['Course Number'] = C1_filter
WP_PE6_avg['Course Number'] = C1_filter
# PE7
CB_PE7_avg['Course Number'] = C2_filter
PW_PE7_avg['Course Number'] = C2_filter
WP_PE7_avg['Course Number'] = C2_filter
# PE8
CB_PE8_avg['Course Number'] = C3_filter
PW_PE8_avg['Course Number'] = C3_filter
WP_PE8_avg['Course Number'] = C3_filter

# Add a new column named 'Course Name' with value of the originally filtered course for all rows
# PE6
CB_PE6_avg['Course Name'] = C1_name
PW_PE6_avg['Course Name'] = C1_name
WP_PE6_avg['Course Name'] = C1_name
# PE7
CB_PE7_avg['Course Name'] = C2_name
PW_PE7_avg['Course Name'] = C2_name
WP_PE7_avg['Course Name'] = C2_name
# PE8
CB_PE8_avg['Course Name'] = C3_name
PW_PE8_avg['Course Name'] = C3_name
WP_PE8_avg['Course Name'] = C3_name

# Add a new column named 'EarnedCrHrs' with value '0.5' for all rows
# PE6
CB_PE6_avg['EarnedCrHrs'] = 0.5
PW_PE6_avg['EarnedCrHrs'] = 0.5
WP_PE6_avg['EarnedCrHrs'] = 0.5
# PE7
CB_PE7_avg['EarnedCrHrs'] = 0.5
PW_PE7_avg['EarnedCrHrs'] = 0.5
WP_PE7_avg['EarnedCrHrs'] = 0.5
# PE8
CB_PE8_avg['EarnedCrHrs'] = 0.5
PW_PE8_avg['EarnedCrHrs'] = 0.5
WP_PE8_avg['EarnedCrHrs'] = 0.5

# Add a new column named 'PotentialCrHrs' with value '0.5' for all rows
# PE6
CB_PE6_avg['PotentialCrHrs'] = 0.5
PW_PE6_avg['PotentialCrHrs'] = 0.5
WP_PE6_avg['PotentialCrHrs'] = 0.5
# PE7
CB_PE7_avg['PotentialCrHrs'] = 0.5
PW_PE7_avg['PotentialCrHrs'] = 0.5
WP_PE7_avg['PotentialCrHrs'] = 0.5
# PE8
CB_PE8_avg['PotentialCrHrs'] = 0.5
PW_PE8_avg['PotentialCrHrs'] = 0.5
WP_PE8_avg['PotentialCrHrs'] = 0.5

# Add a new column named 'Grade_Level' with value '6' for all rows
# PE6
CB_PE6_avg['Grade_Level'] = 6
PW_PE6_avg['Grade_Level'] = 6
WP_PE6_avg['Grade_Level'] = 6
# PE7
CB_PE7_avg['Grade_Level'] = 7
PW_PE7_avg['Grade_Level'] = 7
WP_PE7_avg['Grade_Level'] = 7
# PE8
CB_PE8_avg['Grade_Level'] = 8
PW_PE8_avg['Grade_Level'] = 8
WP_PE8_avg['Grade_Level'] = 8

# Add a new column named 'CreditType' with value '0.5' for all rows
# PE6
CB_PE6_avg['CreditType'] = 'PE'
PW_PE6_avg['CreditType'] = 'PE'
WP_PE6_avg['CreditType'] = 'PE'
# PE7
CB_PE7_avg['CreditType'] = 'PE'
PW_PE7_avg['CreditType'] = 'PE'
WP_PE7_avg['CreditType'] = 'PE'
# PE8
CB_PE8_avg['CreditType'] = 'PE'
PW_PE8_avg['CreditType'] = 'PE'
WP_PE8_avg['CreditType'] = 'PE'

# Add a new column named 'StoreCode' with value 'Y1' for all rows
# PE6
CB_PE6_avg['StoreCode'] = 'Y1'
PW_PE6_avg['StoreCode'] = 'Y1'
WP_PE6_avg['StoreCode'] = 'Y1'
# PE7
CB_PE7_avg['StoreCode'] = 'Y1'
PW_PE7_avg['StoreCode'] = 'Y1'
WP_PE7_avg['StoreCode'] = 'Y1'
# PE8
CB_PE8_avg['StoreCode'] = 'Y1'
PW_PE8_avg['StoreCode'] = 'Y1'
WP_PE8_avg['StoreCode'] = 'Y1'

# Add a new column named 'TermID' with value '3300' for all rows
# PE6
CB_PE6_avg['TermID'] = 3300
PW_PE6_avg['TermID'] = 3300
WP_PE6_avg['TermID'] = 3300
# PE7
CB_PE7_avg['TermID'] = 3300
PW_PE7_avg['TermID'] = 3300
WP_PE7_avg['TermID'] = 3300
# PE8
CB_PE8_avg['TermID'] = 3300
PW_PE8_avg['TermID'] = 3300
WP_PE8_avg['TermID'] = 3300

# Add a new column named 'SchoolID' with value 255 for CB, 260 for PW and 265 for WP for all rows
# PE6
CB_PE6_avg['SchoolID'] = 255
PW_PE6_avg['SchoolID'] = 260
WP_PE6_avg['SchoolID'] = 265
# PE7
CB_PE7_avg['SchoolID'] = 255
PW_PE7_avg['SchoolID'] = 260
WP_PE7_avg['SchoolID'] = 265
# PE8
CB_PE8_avg['SchoolID'] = 255
PW_PE8_avg['SchoolID'] = 260
WP_PE8_avg['SchoolID'] = 265



CB_PE6_avg.head()

,Avg_Percent,Letter Grade,GPA Points,Course Number,Course Name,EarnedCrHrs,PotentialCrHrs,Grade_Level,CreditType,StoreCode,TermID,SchoolID
StudentID,,,,,,,,,,,,
7393,67.727500,D,1,PE6,Phys Ed 6th,0.5,0.5,6,PE,Y1,3300,255
7397,98.292500,A,4,PE6,Phys Ed 6th,0.5,0.5,6,PE,Y1,3300,255
7752,100.000000,A,4,PE6,Phys Ed 6th,0.5,0.5,6,PE,Y1,3300,255
7849,99.715000,A,4,PE6,Phys Ed 6th,0.5,0.5,6,PE,Y1,3300,255
7874,99.243333,A,4,PE6,Phys Ed 6th,0.5,0.5,6,PE,Y1,3300,255

This last code segment creates a folder named "Prepared Uploads" if it doesn't exist and exports each processed DataFrame (student grades with additional info) to a separate CSV file within that folder. The filenames are descriptive and based on the DataFrame names.

In [21]:
# Path to the output CSV file (replace with your desired name and location)

# Create the folder "Prepared Uploads" if it doesn't exist
output_folder = "Prepared Uploads"
if not os.path.exists(output_folder):
    os.makedirs(output_folder)  # Create the folder using makedirs

# Path to the output CSV file (replace with your desired name)
csv_filenames = {
    "CB_PE6_avg": "CB_PE6_AVG_Grades_Upload.csv",
    "PW_PE6_avg": "PW_PE6_AVG_Grades_Upload.csv",
    "WP_PE6_avg": "WP_PE6_AVG_Grades_Upload.csv",
    "CB_PE7_avg": "CB_PE7_AVG_Grades_Upload.csv",
    "PW_PE7_avg": "PW_PE7_AVG_Grades_Upload.csv",
    "WP_PE7_avg": "WP_PE7_AVG_Grades_Upload.csv",
    "CB_PE8_avg": "CB_PE8_AVG_Grades_Upload.csv",
    "PW_PE8_avg": "PW_PE8_AVG_Grades_Upload.csv",
    "WP_PE8_avg": "WP_PE8_AVG_Grades_Upload.csv",
}

# Export the result to a new CSV file with folder inclusion
for key, filename in csv_filenames.items():
    filepath = os.path.join(output_folder, filename)  # Join folder path and filename
    getattr(eval(key), 'to_csv')(filepath)  # Dynamically call to_csv with filepath
    print(f"{filename} created successfully in {output_folder}")  # Informative message

CB_PE6_AVG_Grades_Upload.csv created successfully in Prepared Uploads
PW_PE6_AVG_Grades_Upload.csv created successfully in Prepared Uploads
WP_PE6_AVG_Grades_Upload.csv created successfully in Prepared Uploads
CB_PE7_AVG_Grades_Upload.csv created successfully in Prepared Uploads
PW_PE7_AVG_Grades_Upload.csv created successfully in Prepared Uploads
WP_PE7_AVG_Grades_Upload.csv created successfully in Prepared Uploads
CB_PE8_AVG_Grades_Upload.csv created successfully in Prepared Uploads
PW_PE8_AVG_Grades_Upload.csv created successfully in Prepared Uploads
WP_PE8_AVG_Grades_Upload.csv created successfully in Prepared Uploads